apiVersion: v1
kind: Secret
metadata:
 name: medusa-bucket-key
 namespace: k8ssandra-operator
type: Opaque
stringData:
 # Note that this currently has to be set to credentials!
 credentials: |-
   [default]
   aws_access_key_id = admin
   aws_secret_access_key = kineticdata